'use client';

import { Archive, BookOpenCheck, CheckCircle2, ExternalLink, Lightbulb, MapPin, Pencil, ShieldCheck, Trash2, X } from 'lucide-react';

import { Button } from '@/components/ui/button';
import type { GrammarExercise, VocabularyItem } from '@/lib/types';

const statusLabel = { verified: 'Geprüft', corrected: 'Korrigiert', nuance: 'Mit Hinweis' } as const;

export function VocabularyDetail({ word, exercises, onClose, onEdit, onPractice, onArchive, onDelete }: { word: VocabularyItem; exercises: GrammarExercise[]; onClose: () => void; onEdit: () => void; onPractice: (items: GrammarExercise[]) => void; onArchive: () => void; onDelete: () => void }) {
  const grammar = exercises.filter((exercise) => exercise.kind !== 'sentence');
  const sentences = exercises.filter((exercise) => exercise.kind === 'sentence');
  return <dialog open className="fixed inset-0 z-50 m-0 grid h-full max-h-none w-full max-w-none place-items-center border-0 bg-[#082b28]/60 p-3 backdrop-blur-sm"><div className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-card text-foreground shadow-2xl">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b bg-card/95 p-4 backdrop-blur"><div><p className="text-xs text-muted-foreground">{word.category}</p><h2 className="font-heading text-3xl font-bold text-primary">{word.target}</h2><p className="text-sm text-muted-foreground">{word.translation}</p></div><Button size="icon" variant="ghost" onClick={onClose}><X /></Button></header>
    <div className="space-y-5 p-5">
      <div className="flex flex-wrap gap-2">{word.cefrLevel && <span className="rounded-full bg-primary/8 px-3 py-1 text-xs font-bold text-primary">{word.cefrLevel}</span>}{word.languageGuidance && <><span className="rounded-full bg-muted px-3 py-1 text-xs">{word.languageGuidance.register === 'respectful' ? 'respektvoll' : word.languageGuidance.register === 'polite' ? 'höflich' : word.languageGuidance.register === 'informal' ? 'informell' : 'neutral'}</span><span className="rounded-full bg-muted px-3 py-1 text-xs">{word.languageGuidance.useMode === 'active' ? 'aktiv sprechen' : 'zuerst verstehen'}</span></>}</div>
      {word.verification && <div className="flex gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-4"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><strong className="text-sm">{statusLabel[word.verification.status]}</strong><p className="mt-1 text-sm text-muted-foreground">{word.verification.note}</p></div></div>}
      {word.responseTarget && <div className="rounded-2xl border border-primary/15 bg-primary/5 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Passende Antwort</p><strong className="mt-2 block text-lg">{word.responseTarget}</strong><p className="text-sm text-muted-foreground">{word.responseTranslation}</p></div>}
      {word.exampleTarget && <div className="rounded-2xl bg-muted p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Im Satz</p><strong className="mt-2 block text-lg">{word.exampleTarget}</strong><p className="text-sm text-muted-foreground">{word.exampleTranslation}</p></div>}
      {(word.lemma || word.nounClass) && <div className="grid gap-3 sm:grid-cols-2">{word.lemma && <div className="rounded-2xl border p-4"><span className="text-xs text-muted-foreground">Grundform</span><strong className="mt-1 block text-lg">{word.lemma}</strong></div>}<div className="rounded-2xl border p-4"><span className="text-xs text-muted-foreground">{word.nounClass ? 'Nomenklasse' : 'Wortart'}</span><strong className="mt-1 block text-lg">{word.nounClass ?? (word.partOfSpeech === 'verb' ? 'Verb' : word.partOfSpeech ?? 'Ausdruck')}</strong></div></div>}
      {word.languageGuidance && <section className="space-y-3"><div className="rounded-2xl border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Standard-Swahili</p><p className="mt-2 text-sm leading-relaxed">{word.languageGuidance.standard}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border p-4"><strong className="text-sm">Warum ist das so?</strong><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{word.languageGuidance.why}</p></div><div className="rounded-2xl border border-[#ead4a4] bg-[#fff8e8] p-4"><strong className="text-sm text-[#7c5b20]">Typischer Anfängerfehler</strong><p className="mt-2 text-sm leading-relaxed text-[#756747]">{word.languageGuidance.commonMistake}</p></div></div><div className="rounded-2xl border p-4"><div className="flex items-center gap-2"><MapPin className="size-4 text-primary" /><strong className="text-sm">Paje & Michamvi</strong><span className="ml-auto rounded-full bg-muted px-2 py-1 text-[10px] font-semibold">{word.languageGuidance.regionalStatus === 'local-verified' ? 'lokal bestätigt' : word.languageGuidance.regionalStatus === 'local-review' ? 'lokal noch prüfen' : 'standard-sicher'}</span></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{word.languageGuidance.localUsage}</p>{word.languageGuidance.sourceUrl && <a className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline" href={word.languageGuidance.sourceUrl} target="_blank" rel="noreferrer">{word.languageGuidance.sourceLabel} <ExternalLink className="size-3" /></a>}</div></section>}
      {exercises.length ? <div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Aktiv trainieren</p><h3 className="font-heading text-2xl font-bold">Übungen zu diesem Wort</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><button className="rounded-2xl border bg-card p-4 text-left transition hover:border-primary/30 hover:shadow-md" onClick={() => onPractice(grammar)}><BookOpenCheck className="size-5 text-primary" /><strong className="mt-3 block">Grammatik üben</strong><span className="text-sm text-muted-foreground">{grammar.length} Aufgaben: Formen, Verneinung, Aufbau</span></button><button disabled={!sentences.length} className="rounded-2xl border bg-card p-4 text-left transition hover:border-primary/30 hover:shadow-md disabled:opacity-45" onClick={() => onPractice(sentences)}><CheckCircle2 className="size-5 text-primary" /><strong className="mt-3 block">Satz üben</strong><span className="text-sm text-muted-foreground">Den Beispielsatz selbst bilden und prüfen</span></button></div></div> : <div className="rounded-2xl border border-dashed p-5 text-sm text-muted-foreground">Für dieses Wort gibt es noch kein Verbprofil. Du kannst weiterhin einen Beispielsatz und eigene Hinweise hinterlegen.</div>}
      {(word.personalMnemonic || word.mnemonicSuggestion) && <div className="flex gap-3 rounded-2xl border border-[#ead4a4] bg-[#fff8e8] p-4"><Lightbulb className="size-5 shrink-0 text-[#8d651d]" /><p className="text-sm">{word.personalMnemonic || word.mnemonicSuggestion}</p></div>}
    </div>
    <footer className="grid gap-2 border-t p-4 sm:grid-cols-[1fr_auto_auto]"><Button variant="outline" className="rounded-xl" onClick={onEdit}><Pencil /> Vokabel bearbeiten</Button><Button variant="outline" className="rounded-xl" onClick={onArchive}><Archive /> Aus Lernplan</Button><Button variant="ghost" className="rounded-xl text-destructive hover:text-destructive" onClick={onDelete}><Trash2 /> Löschen</Button></footer>
  </div></dialog>;
}
