import type { LearningPack } from '@/lib/types';

export const learningPacks: LearningPack[] = [
  {
    id: 'a1-greetings',
    level: 'A1',
    order: 1,
    title: 'Begrüßen & höflich sein',
    goal: 'Du kannst ein Gespräch respektvoll beginnen, passend antworten und höflich reagieren.',
    vocabularyIds: [
      'sw-056',
      'sw-057',
      'sw-058',
      'sw-059',
      'sw-060',
      'sw-061',
      'sw-062',
    ],
    prerequisiteIds: [],
    activation: 'on-start',
  },
  {
    id: 'a1-everyday-verbs',
    level: 'A1',
    order: 2,
    title: 'Mein Alltag in Verben',
    goal: 'Du sagst, was du tust, möchtest und als Nächstes vorhast.',
    vocabularyIds: [
      'sw-001',
      'sw-002',
      'sw-003',
      'sw-004',
      'sw-005',
      'sw-006',
      'sw-038',
    ],
    prerequisiteIds: [],
    activation: 'already-active',
  },
  {
    id: 'a1-day-times',
    level: 'A1',
    order: 3,
    title: 'Tageszeiten & passende Grüße',
    goal: 'Du ordnest Morgen, Tag, Nachmittag, Abend und Nacht richtig ein.',
    vocabularyIds: [
      'sw-007',
      'sw-008',
      'sw-009',
      'sw-010',
      'sw-011',
      'sw-012',
      'sw-055',
    ],
    prerequisiteIds: ['a1-greetings'],
    activation: 'already-active',
  },
  {
    id: 'a1-weekdays',
    level: 'A1',
    order: 4,
    title: 'Wochentage & Planung',
    goal: 'Du verstehst und nennst jeden Wochentag für einfache Verabredungen.',
    vocabularyIds: [
      'sw-013',
      'sw-014',
      'sw-015',
      'sw-016',
      'sw-017',
      'sw-018',
      'sw-019',
    ],
    supportingVocabularyIds: ['sw-029'],
    prerequisiteIds: [],
    activation: 'already-active',
  },
  {
    id: 'a1-food-market',
    level: 'A1',
    order: 5,
    title: 'Essen, bestellen & Markt',
    goal: 'Du äußerst Bedürfnisse, bestellst höflich und bewältigst einen einfachen Einkauf.',
    vocabularyIds: [
      'sw-024',
      'sw-025',
      'sw-026',
      'sw-030',
      'sw-031',
      'sw-033',
      'sw-034',
    ],
    supportingVocabularyIds: ['sw-021', 'sw-022', 'sw-023', 'sw-028', 'sw-032'],
    prerequisiteIds: ['a1-everyday-verbs'],
    activation: 'already-active',
  },
  {
    id: 'a1-contact-help',
    level: 'A1',
    order: 6,
    title: 'Kontakt, Fragen & Hilfe',
    goal: 'Du stellst eine Frage, dankst, wartest, hilfst und hältst Kontakt.',
    vocabularyIds: [
      'sw-037',
      'sw-040',
      'sw-042',
      'sw-043',
      'sw-044',
      'sw-045',
      'sw-050',
    ],
    supportingVocabularyIds: ['sw-020', 'sw-035', 'sw-036', 'sw-041'],
    prerequisiteIds: ['a1-everyday-verbs'],
    activation: 'already-active',
  },
  {
    id: 'a1-meeting-location',
    level: 'A1',
    order: 7,
    title: 'Treffen & Orientierung',
    goal: 'Du fragst nach dem Ort, klärst Bereitschaft und koordinierst ein Treffen.',
    vocabularyIds: [
      'sw-027',
      'sw-047',
      'sw-049',
      'sw-051',
      'sw-052',
      'sw-053',
      'sw-054',
    ],
    supportingVocabularyIds: ['sw-039', 'sw-046', 'sw-048'],
    prerequisiteIds: ['a1-everyday-verbs'],
    activation: 'already-active',
  },
];
