import { newCard } from '@/lib/scheduler';
import type { VocabularyItem } from '@/lib/types';
import { auditVocabulary } from '@/lib/vocabulary-audit';

type SeedRow = [string, string, string, string?, string?, string?];

const rows: SeedRow[] = [
  ['naenda', 'ich gehe', 'Verben', 'Ninaenda sokoni.', 'Ich gehe zum Markt.', 'Na-end-a: Stell dir vor, du gehst ans Ende einer Straße.'],
  ['napenda', 'ich mag / ich liebe', 'Verben', 'Napenda Zanzibar.', 'Ich mag Sansibar.', 'Klingt wie: Na, Panda! Den Panda magst du.'],
  ['nataka', 'ich möchte / ich will', 'Verben', 'Nataka kahawa.', 'Ich möchte Kaffee.', 'Du möchtest eine TAKA-Tasse Kaffee.'],
  ['nakuja', 'ich komme', 'Verben', 'Nakuja sasa.', 'Ich komme jetzt.', 'Na, KUJA – komm her!'],
  ['nakula', 'ich esse', 'Verben', 'Nakula wali.', 'Ich esse Reis.', 'KULA klingt wie kulinarisch.'],
  ['kuonana', 'sich treffen / einander sehen', 'Verben', 'Tutaonana kesho.', 'Wir sehen uns morgen.', ''],
  ['asubuhi', 'am Morgen', 'Zeit', 'Habari za asubuhi?', 'Guten Morgen, wie geht es?', 'Am Morgen ist alles super-hi.'],
  ['mchana', 'am Tag / mittags', 'Zeit', 'Habari za mchana?', 'Guten Tag, wie geht es?', ''],
  ['alasiri', 'am Nachmittag', 'Zeit', 'Habari za alasiri?', 'Guten Nachmittag.', ''],
  ['jioni', 'am Abend', 'Zeit', 'Habari za jioni?', 'Guten Abend.', ''],
  ['usiku', 'in der Nacht', 'Zeit', 'Ni usiku sasa.', 'Es ist jetzt Nacht.', ''],
  ['usiku mwema', 'gute Nacht', 'Begrüßung', 'Usiku mwema!', 'Gute Nacht!', 'Usiku = Nacht, mwema = gut.'],
  ['jumamosi', 'Samstag', 'Wochentage'],
  ['jumapili', 'Sonntag', 'Wochentage', '', '', 'Juma pili: der zweite Tag der Swahili-Woche.'],
  ['jumatatu', 'Montag', 'Wochentage'],
  ['jumanne', 'Dienstag', 'Wochentage'],
  ['jumatano', 'Mittwoch', 'Wochentage'],
  ['alhamisi', 'Donnerstag', 'Wochentage'],
  ['ijumaa', 'Freitag', 'Wochentage'],
  ['wewe', 'du / dich', 'Pronomen', 'Ninakuona wewe.', 'Ich sehe dich.', ''],
  ['Ninaenda kununua mkate.', 'Ich gehe Brot kaufen.', 'Unterwegs', '', '', 'nunua = kaufen, mkate = Brot'],
  ['Unanunua mkate.', 'Du kaufst Brot.', 'Unterwegs'],
  ['Tunanunua mkate.', 'Wir kaufen Brot.', 'Unterwegs'],
  ['Ninanunua mkate.', 'Ich kaufe Brot.', 'Unterwegs'],
  ['kifungua kinywa', 'Frühstück', 'Essen', 'Ninakula kifungua kinywa.', 'Ich frühstücke.', 'Wörtlich: das, was den Mund öffnet.'],
  ['Njoo kula!', 'Komm essen!', 'Essen'],
  ['muda', 'Zeit / Zeitraum', 'Zeit', 'Sina muda.', 'Ich habe keine Zeit.', ''],
  ['Ninaenda kupika.', 'Ich gehe kochen.', 'Essen'],
  ['wiki moja', 'eine Woche', 'Zeit'],
  ['Tunaenda sokoni.', 'Wir gehen zum Markt.', 'Unterwegs', '', '', 'soko = Markt, sokoni = auf/zum Markt'],
  ['Naomba maji, tafadhali.', 'Ich möchte Wasser, bitte.', 'Restaurant', '', '', 'naomba = ich bitte, maji = Wasser'],
  ['Nina njaa. / Sina njaa.', 'Ich habe Hunger. / Ich habe keinen Hunger.', 'Essen'],
  ['njaa', 'Hunger', 'Essen'],
  ['kiu', 'Durst', 'Essen', 'Nina kiu.', 'Ich habe Durst.', ''],
  ['furaha', 'Freude / Glück', 'Gefühle'],
  ['huzuni', 'Traurigkeit', 'Gefühle'],
  ['swali', 'Frage', 'Gespräch', 'Nina swali.', 'Ich habe eine Frage.', ''],
  ['kazi', 'Arbeit', 'Alltag', 'Ninaenda kazini.', 'Ich gehe zur Arbeit.', ''],
  ['Nakuja ulipo.', 'Ich komme zu dir / dorthin, wo du bist.', 'Gespräch'],
  ['Ninakushukuru.', 'Ich danke dir.', 'Gespräch', '', '', 'ni-na-ku-shukuru: ich – jetzt – dir – danken'],
  ['Nakupa.', 'Ich gebe dir.', 'Gespräch'],
  ['Nakusubiri.', 'Ich warte auf dich.', 'Gespräch'],
  ['Nakusaidia.', 'Ich helfe dir.', 'Gespräch'],
  ['Nakupigia simu.', 'Ich rufe dich an.', 'Gespräch', '', '', 'simu = Telefon'],
  ['Ninakupa.', 'Ich gebe dir.', 'Gespräch'],
  ['Nimekuona.', 'Ich habe dich gesehen.', 'Gespräch'],
  ['Mimi nipo tayari.', 'Ich bin bereit.', 'Gespräch'],
  ['Sisi tupo tayari.', 'Wir sind bereit.', 'Gespräch'],
  ['Uko tayari?', 'Bist du bereit?', 'Gespräch'],
  ['Wewe ni nani?', 'Wer bist du?', 'Kennenlernen'],
  ['Nakuona!', 'Ich sehe dich!', 'Gespräch'],
  ['Uko wapi?', 'Wo bist du?', 'Unterwegs'],
  ['nipo / niko / nimo', 'ich bin da / an einem Ort / darin', 'Grammatik', '', '', 'po = genauer Ort, ko = allgemeiner Ort, mo = innen'],
  ['Subiri kidogo, narudi sasa hivi.', 'Warte kurz, ich komme gleich zurück.', 'Gespräch', '', '', 'subiri = warte, kidogo = ein wenig, narudi = ich kehre zurück'],
  ['Habari ya jioni?', 'Guten Abend! / Wie geht es heute Abend?', 'Begrüßung', 'Habari ya jioni?', 'Guten Abend!', 'jioni = Abend'],
  ['Habari?', 'Wie geht es? / Was gibt es Neues?', 'A1 · Begrüßung', 'Habari? — Nzuri, asante.', 'Wie geht es? — Gut, danke.', 'Habari bedeutet wörtlich „Neuigkeiten“.'],
  ['Hujambo?', 'Geht es dir gut?', 'A1 · Begrüßung', 'Hujambo? — Sijambo.', 'Geht es dir gut? — Mir geht es gut.', 'HU-jambo fragt nach dir, SI-jambo antwortet für mich.'],
  ['Shikamoo. — Marahaba.', 'Respektvolle Begrüßung einer älteren Person und Antwort', 'A1 · Begrüßung', 'Shikamoo, mama. — Marahaba.', 'Respektvolle Begrüßung und Antwort.', 'Dieses Paar gehört zusammen: Shikamoo – Marahaba.'],
  ['Asante sana.', 'Vielen Dank.', 'A1 · Höflichkeit', 'Asante sana kwa msaada.', 'Vielen Dank für die Hilfe.', 'sana verstärkt: sehr / viel.'],
  ['Tafadhali.', 'Bitte.', 'A1 · Höflichkeit', 'Maji, tafadhali.', 'Wasser, bitte.', 'Tafadhali macht eine Bitte höflicher.'],
  ['Samahani.', 'Entschuldigung / Verzeihung.', 'A1 · Höflichkeit', 'Samahani, unaweza kunisaidia?', 'Entschuldigung, kannst du mir helfen?', 'Samahani öffnet höflich eine Frage oder entschuldigt.'],
  ['Karibu! / Karibuni!', 'Willkommen! – eine Person / mehrere Personen', 'A1 · Höflichkeit', 'Karibu ukae. / Karibuni mkae.', 'Setz dich gern. / Setzt euch gern.', 'Die Endung -ni richtet sich an mehrere Personen.'],
];

const originalCorrections: Record<number, string> = {
  3: 'Quelle: nattaka', 7: 'Quelle: azubui', 8: 'Quelle enthielt „za siku 09–18“',
  9: 'Quelle enthielt „za machana 12–15“', 10: 'Quelle: alhasiri', 11: 'Quelle ordnete usiku dem Abend zu',
  12: 'Quelle: uziku', 17: 'Quelle: jumane', 19: 'Quelle: alahamisi', 20: 'Quelle: ijuma',
  22: 'Quelle: kunnunua', 25: 'Quelle: kunnunua mukate', 31: 'Quelle: tonaenda sokony',
  46: 'Doppelter Eintrag in der Quelle', 47: 'Quelle übersetzte Präsens; Form ist Perfekt',
  55: 'Quelle enthielt mehrere Varianten',
};

export function createSeedVocabulary(now = new Date()): VocabularyItem[] {
  return auditVocabulary(rows.map(([target, translation, category, exampleTarget, exampleTranslation, mnemonicSuggestion], index) => ({
    id: `sw-${String(index + 1).padStart(3, '0')}`,
    language: 'sw',
    target,
    translation,
    category,
    exampleTarget: exampleTarget || undefined,
    exampleTranslation: exampleTranslation || undefined,
    mnemonicSuggestion: mnemonicSuggestion || undefined,
    morphemes: target === 'Ninakushukuru.' ? ['ni', 'na', 'ku', 'shukuru'] : undefined,
    notes: originalCorrections[index + 1],
    sourceText: originalCorrections[index + 1],
    needsReview: Boolean(originalCorrections[index + 1]),
    card: newCard(now),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  })));
}
